FROM amazon/aws-for-fluent-bit:main-debug-base
COPY ./scripts/dockerfiles/Dockerfile.main-debug-base /Dockerfile.2.main-debug-base

# Default: Run under valgrind
# alternatively, you can change this to run FB directly and try
# to get a core file instead
CMD valgrind --leak-check=full --error-limit=no /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
